# Generated by Django 3.1.3 on 2020-12-05 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_auto_20201205_1722'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Kolegij', 'verbose_name_plural': 'Kolegiji'},
        ),
        migrations.RemoveField(
            model_name='subject',
            name='optional',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='programs',
        ),
        migrations.CreateModel(
            name='SubjectPrograms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optional', models.BooleanField(verbose_name='Izborni kolegij')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.program', verbose_name='Program')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject', verbose_name='Kolegij')),
            ],
            options={
                'verbose_name': 'Programi po kolegiju',
                'verbose_name_plural': 'Programi po kolegijima',
            },
        ),
    ]
