# Generated by Django 3.1.3 on 2020-12-23 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='dinp_link',
            field=models.CharField(max_length=254, null=True, verbose_name='DINP - Download link'),
        ),
        migrations.AddField(
            model_name='subject',
            name='predavanja_dan',
            field=models.CharField(choices=[('ponedjeljkom', 'Ponedjeljak'), ('utorkom', 'Utorak'), ('srijedom', 'Srijeda'), ('četvrtkom', 'Četvrtak'), ('petkom', 'Petak'), ('subotom', 'Subota'), ('nedjeljom', 'Nedjelja')], max_length=64, null=True, verbose_name='Predavanja - dan u tjednu'),
        ),
        migrations.AddField(
            model_name='subject',
            name='predavanja_trajanje',
            field=models.DurationField(default='1:30', verbose_name='Predavanja - trajanje'),
        ),
        migrations.AddField(
            model_name='subject',
            name='predavanja_vrijeme',
            field=models.TimeField(null=True, verbose_name='Predavanja - vrijeme početka'),
        ),
        migrations.AddField(
            model_name='subject',
            name='vjezbe_dan',
            field=models.CharField(choices=[('ponedjeljkom', 'Ponedjeljak'), ('utorkom', 'Utorak'), ('srijedom', 'Srijeda'), ('četvrtkom', 'Četvrtak'), ('petkom', 'Petak'), ('subotom', 'Subota'), ('nedjeljom', 'Nedjelja')], max_length=64, null=True, verbose_name='Vježbe - dan u tjednu'),
        ),
        migrations.AddField(
            model_name='subject',
            name='vjezbe_trajanje',
            field=models.DurationField(default='1:30', verbose_name='Vježbe - trajanje'),
        ),
        migrations.AddField(
            model_name='subject',
            name='vjezbe_vrijeme',
            field=models.TimeField(null=True, verbose_name='Vježbe - vrijeme početka'),
        ),
    ]
