# Generated by Django 3.1.3 on 2021-01-03 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_auto_20201223_2356'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ('-academic_year',), 'verbose_name': 'Kolegij', 'verbose_name_plural': 'Kolegiji'},
        ),
        migrations.AlterField(
            model_name='subject',
            name='academic_year',
            field=models.IntegerField(choices=[(2021, '2021/2022'), (2020, '2020/2021'), (2019, '2019/2020')], verbose_name='Akademska godina'),
        ),
    ]
