# Generated by Django 3.1.3 on 2021-02-19 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_auto_20210103_2324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ('code',), 'verbose_name': 'Kolegij', 'verbose_name_plural': 'Kolegiji'},
        ),
        migrations.RemoveField(
            model_name='subject',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='semester',
        ),
        migrations.AddField(
            model_name='subjectprograms',
            name='academic_year',
            field=models.IntegerField(choices=[(2021, '2021/2022'), (2020, '2020/2021'), (2019, '2019/2020')], default=2020, verbose_name='Akademska godina'),
        ),
        migrations.AddField(
            model_name='subjectprograms',
            name='semester',
            field=models.CharField(choices=[('1', '1. semester'), ('2', '2. semester'), ('3', '3. semester'), ('4', '4. semester'), ('5', '5. semester'), ('6', '6. semester')], max_length=1, null=True, verbose_name='Semestar'),
        ),
    ]
