# Generated by Django 3.1.3 on 2021-03-01 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_auto_20210130_1849'),
        ('subjects', '0004_auto_20210219_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectprograms',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Veza aktivna'),
        ),
        migrations.AlterUniqueTogether(
            name='subjectprograms',
            unique_together={('subject', 'program', 'active')},
        ),
    ]
