# Generated by Django 3.1.3 on 2020-12-13 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studying_year', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)], verbose_name='Godina studija')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.program', verbose_name='Program')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Django korisnik')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Studenti',
            },
        ),
        migrations.CreateModel(
            name='StudentSubjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_accomplished', models.FloatField(default=0, verbose_name='Osvojeni bodovi')),
                ('points_total', models.FloatField(default=0, verbose_name='Ukupno bodovi')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student', verbose_name='Student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject', verbose_name='Kolegij')),
            ],
            options={
                'verbose_name': 'Student - Kolegiji',
                'verbose_name_plural': 'Studenti - Kolegiji',
            },
        ),
    ]
