# Generated by Django 3.1.3 on 2020-12-05 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
        ('departments', '0002_auto_20201205_1722'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studying_year', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)], verbose_name='Godina studija')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.program', verbose_name='Program')),
                ('subjects', models.ManyToManyField(to='subjects.Subject', verbose_name='Upisani kolegiji')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Django korisnik')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Studenti',
            },
        ),
    ]
