# Generated by Django 3.1.3 on 2020-12-24 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_auto_20201223_2356'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsubjects',
            name='academic_year',
            field=models.IntegerField(choices=[], default=2020, verbose_name='Akademska godina'),
        ),
        migrations.AlterUniqueTogether(
            name='studentsubjects',
            unique_together={('student', 'subject', 'academic_year')},
        ),
    ]
