# Generated by Django 3.1.3 on 2021-10-21 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_studentsubjects_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsubjects',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Aktivan'),
        ),
    ]
