# Generated by Django 3.1.3 on 2020-12-13 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities_score', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalscoreactivity',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Predano'),
        ),
        migrations.AddField(
            model_name='studentscoreactivity',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Predano'),
        ),
    ]
