# Generated by Django 3.1.3 on 2020-12-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities_score', '0002_auto_20201213_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentscoreactivity',
            name='details',
            field=models.TextField(blank=True, null=True, verbose_name='Dodatne informacije'),
        ),
    ]
