# Generated by Django 3.1.3 on 2021-01-13 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201224_0157'),
        ('activities_score', '0004_auto_20201223_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalscoreactivity',
            name='completed',
            field=models.BooleanField(null=True, verbose_name='Predano'),
        ),
        migrations.AlterField(
            model_name='studentscoreactivity',
            name='completed',
            field=models.BooleanField(null=True, verbose_name='Predano'),
        ),
        migrations.AlterField(
            model_name='studentscoreactivity',
            name='global_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activities_score.globalscoreactivity', verbose_name='Bodovna aktivnost'),
        ),
        migrations.AlterField(
            model_name='studentscoreactivity',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student', verbose_name='Student'),
        ),
    ]
