# Generated by Django 3.1.3 on 2021-01-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities_score', '0005_auto_20210113_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalscoreactivity',
            name='due_date',
            field=models.DateField(null=True, verbose_name='Datum'),
        ),
        migrations.AlterField(
            model_name='globalscoreactivity',
            name='type',
            field=models.IntegerField(choices=[(0, 'Kolokvij'), (1, 'Završni ispit'), (2, 'Seminar'), (3, 'Prezentacija'), (4, 'Domaća zadaća'), (5, 'Laboratorijske vježbe'), (6, 'Rasprava'), (7, 'Projekt'), (8, 'Grupni rad'), (9, 'Kviz'), (10, 'Aktivnost'), (11, 'Popravna aktivnost'), (12, 'Ostalo')], verbose_name='Tip aktivnosti'),
        ),
        migrations.AlterField(
            model_name='studentscoreactivity',
            name='type',
            field=models.IntegerField(choices=[(0, 'Kolokvij'), (1, 'Završni ispit'), (2, 'Seminar'), (3, 'Prezentacija'), (4, 'Domaća zadaća'), (5, 'Laboratorijske vježbe'), (6, 'Rasprava'), (7, 'Projekt'), (8, 'Grupni rad'), (9, 'Kviz'), (10, 'Aktivnost'), (11, 'Popravna aktivnost'), (12, 'Ostalo')], verbose_name='Tip aktivnosti'),
        ),
    ]
