# Generated by Django 3.1.3 on 2021-01-17 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities_score', '0006_auto_20210117_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalscoreactivity',
            name='group',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Grupa'),
        ),
        migrations.AddField(
            model_name='studentscoreactivity',
            name='group',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Grupa'),
        ),
    ]
