# Generated by Django 3.1.3 on 2021-03-01 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities_score', '0007_auto_20210117_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalscoreactivity',
            name='type',
            field=models.IntegerField(choices=[(0, 'Kolokvij'), (1, 'Završni ispit'), (2, 'Seminar'), (3, 'Prezentacija'), (4, 'Domaća zadaća'), (5, 'Samoprovjera'), (6, 'Laboratorijske vježbe'), (7, 'Rasprava'), (8, 'Projekt'), (9, 'Grupni rad'), (10, 'Kviz'), (11, 'Aktivnost'), (12, 'Popravna aktivnost'), (13, 'Ostalo')], verbose_name='Tip aktivnosti'),
        ),
        migrations.AlterField(
            model_name='studentscoreactivity',
            name='type',
            field=models.IntegerField(choices=[(0, 'Kolokvij'), (1, 'Završni ispit'), (2, 'Seminar'), (3, 'Prezentacija'), (4, 'Domaća zadaća'), (5, 'Samoprovjera'), (6, 'Laboratorijske vježbe'), (7, 'Rasprava'), (8, 'Projekt'), (9, 'Grupni rad'), (10, 'Kviz'), (11, 'Aktivnost'), (12, 'Popravna aktivnost'), (13, 'Ostalo')], verbose_name='Tip aktivnosti'),
        ),
    ]
