# Generated by Django 3.1.3 on 2021-03-03 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities_score', '0008_auto_20210301_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalscoreactivity',
            name='active',
            field=models.BooleanField(null=True, verbose_name='Aktivan'),
        ),
        migrations.AddField(
            model_name='studentscoreactivity',
            name='active',
            field=models.BooleanField(null=True, verbose_name='Aktivan'),
        ),
    ]
