# Generated by Django 3.1.3 on 2020-12-05 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Naziv')),
                ('code', models.CharField(max_length=8, verbose_name='Kod')),
                ('address', models.TextField(verbose_name='Adreasa')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('contact', models.CharField(max_length=16, verbose_name='Kontakt broj')),
                ('web', models.CharField(max_length=254, verbose_name='Web')),
            ],
            options={
                'verbose_name': 'Odjel',
                'verbose_name_plural': 'Odjeli',
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Naziv')),
                ('code', models.CharField(max_length=8, verbose_name='Kod')),
                ('address', models.TextField(verbose_name='Adresa')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('contact', models.CharField(max_length=16, verbose_name='Kontakt broj')),
            ],
            options={
                'verbose_name': 'Sveučilište',
                'verbose_name_plural': 'Sveučilišta',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Naziv')),
                ('type', models.CharField(choices=[('preddiplomski', 'Preddiplomski'), ('diplomski', 'Diplomski')], max_length=50, verbose_name='Tip programa')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.department', verbose_name='Odjel')),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Programi',
            },
        ),
        migrations.AddField(
            model_name='department',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.university', verbose_name='Sveučilište'),
        ),
    ]
