# Generated by Django 3.1.3 on 2020-12-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'verbose_name': 'Studij', 'verbose_name_plural': 'Studiji'},
        ),
        migrations.AlterField(
            model_name='program',
            name='type',
            field=models.CharField(choices=[('preddiplomski', 'Preddiplomski'), ('diplomski', 'Diplomski')], max_length=50, verbose_name='Tip studija'),
        ),
    ]
