# Generated by Django 3.1.3 on 2020-12-28 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities_class', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentclassactivity',
            name='attended',
            field=models.BooleanField(default=False, verbose_name='Prisustvo'),
        ),
    ]
