# Generated by Django 3.1.3 on 2020-12-28 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities_class', '0002_studentclassactivity_attended'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalclassactivity',
            name='attended',
            field=models.BooleanField(default=False, verbose_name='Prisustvo'),
        ),
    ]
