# Generated by Django 3.1.3 on 2021-01-17 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities_class', '0003_globalclassactivity_attended'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalclassactivity',
            name='group',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Grupa'),
        ),
        migrations.AddField(
            model_name='studentclassactivity',
            name='group',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Grupa'),
        ),
    ]
