# Generated by Django 3.1.3 on 2021-10-21 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities_class', '0005_auto_20210303_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalclassactivity',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Aktivan'),
        ),
        migrations.AlterField(
            model_name='studentclassactivity',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Aktivan'),
        ),
    ]
